version: "3.7"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: yiidb
      MYSQL_USER: yiiuser
      MYSQL_PASSWORD: yiipwd
    volumes:
      - ./data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - app-network
  
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: yiiuser
      PMA_PASSWORD: yiipwd
    networks:
      - app-network
  
  app:
    depends_on:
      - mysql
    build: .
    restart: always
    stdin_open: true
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./conf/app.conf:/usr/local/etc/php-fpm.d/www.conf
    command: ""
    expose: 
      - 9000
    networks:
      - app-network
      
  nginx:
    depends_on:
      - mysql
      - app
    image: nginx:alpine
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www/html
    ports:
      - 80:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge